version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - JWT_SECRET_KEY
      - JWT_REFRESH_SECRET_KEY
      - REDIS_URL
      - ENVIRONMENT
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: auth-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_URL##*:}
      POSTGRES_PASSWORD: ${DATABASE_URL#*:}
      POSTGRES_DB: ${DATABASE_URL##*/}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  postgres_data:
  redis_data:
