"""Extend user model for social auth

Revision ID: 9738913ac48c
Revises: 268c5333e9fd
Create Date: 2025-07-04 12:05:38.955175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9738913ac48c'
down_revision: Union[str, None] = '268c5333e9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('vk_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['yandex_id'])
    op.create_unique_constraint(None, 'users', ['vk_id'])
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'vk_id')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
